// app/dashboard/settings/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/navigation'
import { 
  Card, 
  CardContent, 
  CardDescription, 
  CardHeader, 
  CardTitle 
} from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { 
  AlertCircle, 
  CheckCircle2, 
  Loader2, 
  Store, 
  MapPin, 
  Phone, 
  Mail, 
  FileText,
  Receipt 
} from 'lucide-react'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Separator } from '@/components/ui/separator'

interface Settings {
  id: string
  shopName: string
  address: string
  phone: string
  email: string | null
  gstin: string
  invoicePrefix: string
  currentInvoiceNumber: number
  createdAt: string
  updatedAt: string
}

export default function SettingsPage() {
  const { data: session, status } = useSession()
  const router = useRouter()
  
  const [settings, setSettings] = useState<Settings | null>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [success, setSuccess] = useState(false)
  const [error, setError] = useState('')

  // Form state
  const [formData, setFormData] = useState({
    shopName: '',
    address: '',
    phone: '',
    email: '',
    gstin: '',
    invoicePrefix: '',
  })

  // Fetch settings
  useEffect(() => {
    if (status === 'unauthenticated') {
      router.push('/login')
      return
    }

    fetchSettings()
  }, [status])

  const fetchSettings = async () => {
    try {
      setLoading(true)
      const response = await fetch('/api/settings')
      
      if (!response.ok) {
        throw new Error('Failed to fetch settings')
      }
      
      const data = await response.json()
      setSettings(data)
      setFormData({
        shopName: data.shopName || '',
        address: data.address || '',
        phone: data.phone || '',
        email: data.email || '',
        gstin: data.gstin || '',
        invoicePrefix: data.invoicePrefix || '',
      })
    } catch (err) {
      setError('Failed to load settings')
      console.error(err)
    } finally {
      setLoading(false)
    }
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target
    setFormData(prev => ({ ...prev, [name]: value }))
    setSuccess(false)
    setError('')
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setSaving(true)
    setSuccess(false)
    setError('')

    try {
      const response = await fetch('/api/settings', {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      })

      if (!response.ok) {
        const data = await response.json()
        throw new Error(data.error || 'Failed to update settings')
      }

      const updated = await response.json()
      setSettings(updated)
      setSuccess(true)
      
      // Hide success message after 3 seconds
      setTimeout(() => setSuccess(false), 3000)
    } catch (err: any) {
      setError(err.message || 'Failed to update settings')
    } finally {
      setSaving(false)
    }
  }

  if (status === 'loading' || loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    )
  }

  if (!session) {
    return null
  }

  // Check if user is admin
  if (session.user.role !== 'ADMIN') {
    return (
      <div className="p-6">
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>
            You don't have permission to access this page. Only administrators can modify settings.
          </AlertDescription>
        </Alert>
      </div>
    )
  }

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold tracking-tight">Shop Settings</h1>
        <p className="text-muted-foreground mt-2">
          Manage your shop information that appears on invoices and receipts
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Store className="h-5 w-5" />
            Shop Information
          </CardTitle>
          <CardDescription>
            Update your shop details. These will be used in all invoices generated by the system.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-6">
            {error && (
              <Alert variant="destructive">
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>{error}</AlertDescription>
              </Alert>
            )}

            {success && (
              <Alert className="border-green-500 text-green-700 bg-green-50">
                <CheckCircle2 className="h-4 w-4" />
                <AlertDescription>Settings updated successfully!</AlertDescription>
              </Alert>
            )}

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Shop Name */}
              <div className="space-y-2">
                <Label htmlFor="shopName" className="flex items-center gap-2">
                  <Store className="h-4 w-4" />
                  Shop Name
                </Label>
                <Input
                  id="shopName"
                  name="shopName"
                  value={formData.shopName}
                  onChange={handleChange}
                  placeholder="Enter shop name"
                  required
                />
              </div>

              {/* Phone */}
              <div className="space-y-2">
                <Label htmlFor="phone" className="flex items-center gap-2">
                  <Phone className="h-4 w-4" />
                  Phone Number
                </Label>
                <Input
                  id="phone"
                  name="phone"
                  value={formData.phone}
                  onChange={handleChange}
                  placeholder="Enter phone number"
                  required
                />
              </div>

              {/* Email */}
              <div className="space-y-2">
                <Label htmlFor="email" className="flex items-center gap-2">
                  <Mail className="h-4 w-4" />
                  Email Address
                </Label>
                <Input
                  id="email"
                  name="email"
                  type="email"
                  value={formData.email}
                  onChange={handleChange}
                  placeholder="Enter email address"
                />
              </div>

              {/* GSTIN */}
              <div className="space-y-2">
                <Label htmlFor="gstin" className="flex items-center gap-2">
                  <Receipt className="h-4 w-4" />
                  GSTIN
                </Label>
                <Input
                  id="gstin"
                  name="gstin"
                  value={formData.gstin}
                  onChange={handleChange}
                  placeholder="Enter GSTIN"
                  required
                />
              </div>

              {/* Invoice Prefix */}
              <div className="space-y-2">
                <Label htmlFor="invoicePrefix" className="flex items-center gap-2">
                  <FileText className="h-4 w-4" />
                  Invoice Prefix
                </Label>
                <Input
                  id="invoicePrefix"
                  name="invoicePrefix"
                  value={formData.invoicePrefix}
                  onChange={handleChange}
                  placeholder="e.g., NMC"
                  required
                />
                <p className="text-xs text-muted-foreground">
                  This prefix will be added before invoice numbers (e.g., NMC-1001)
                </p>
              </div>
            </div>

            {/* Address - Full Width */}
            <div className="space-y-2">
              <Label htmlFor="address" className="flex items-center gap-2">
                <MapPin className="h-4 w-4" />
                Shop Address
              </Label>
              <Input
                id="address"
                name="address"
                value={formData.address}
                onChange={handleChange}
                placeholder="Enter complete address"
                required
              />
            </div>

            <Separator />

            {/* Invoice Number Display */}
            {settings && (
              <div className="bg-muted/50 rounded-lg p-4">
                <p className="text-sm font-medium mb-1">Current Invoice Number</p>
                <p className="text-2xl font-bold text-primary">
                  {settings.invoicePrefix}-{settings.currentInvoiceNumber}
                </p>
                <p className="text-xs text-muted-foreground mt-1">
                  Next invoice will use this number. It auto-increments with each new invoice.
                </p>
              </div>
            )}

            {/* Action Buttons */}
            <div className="flex gap-4">
              <Button
                type="submit"
                disabled={saving}
                className="min-w-[150px]"
              >
                {saving ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Saving...
                  </>
                ) : (
                  'Save Changes'
                )}
              </Button>
              
              <Button
                type="button"
                variant="outline"
                onClick={() => {
                  if (settings) {
                    setFormData({
                      shopName: settings.shopName,
                      address: settings.address,
                      phone: settings.phone,
                      email: settings.email || '',
                      gstin: settings.gstin,
                      invoicePrefix: settings.invoicePrefix,
                    })
                  }
                }}
                disabled={saving}
              >
                Reset
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>

      {/* Preview Card */}
      {settings && (
        <Card className="mt-6">
          <CardHeader>
            <CardTitle className="text-lg">Preview</CardTitle>
            <CardDescription>
              This is how your shop information will appear on invoices
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="border rounded-lg p-6 bg-white">
              <div className="text-center space-y-2">
                <h3 className="text-xl font-bold">{formData.shopName || 'Shop Name'}</h3>
                <p className="text-sm text-gray-600">{formData.address || 'Address'}</p>
                <div className="flex justify-center gap-4 text-sm text-gray-600">
                  {formData.phone && <span>📞 {formData.phone}</span>}
                  {formData.email && <span>✉️ {formData.email}</span>}
                </div>
                {formData.gstin && (
                  <p className="text-sm font-medium">GSTIN: {formData.gstin}</p>
                )}
                <div className="border-t pt-2 mt-2">
                  <p className="text-sm text-gray-500">
                    Invoice: {formData.invoicePrefix}-XXXX
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
